initial
DmitriiLebedev/java-shareit pull request #1
Opened 2023-06-20 18:34 UTC by DmitriiLebedev

2023-06-21 11:50 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-06-21 11:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        return items.values().stream().filter(item -> item.getOwner().getId().equals(ownerId))
1)лучше писать так:
..stream().
.filter()
.любой другой метод стримов (то есть каждый писать лучше с новой строчки - так удобнее читать)
2)зачем здесь filter(item -> item.getOwner().getId().equals(ownerId)?

2023-06-21 11:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +
еще нужно хендлить HttpStatus.INTERNAL_SERVER_ERROR

2023-06-21 23:07 UTC, DmitriiLebedev commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        return items.values().stream().filter(item -> item.getOwner().getId().equals(ownerId))
1) сделал перенос
2) это метод это метод выборки всех айтемов по собственнику, просто метод по классике назвал файндОлл, переименовано

2023-06-21 23:07 UTC, DmitriiLebedev commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +
Добавил

2023-06-22 04:38 UTC, ErkinKasymaliev approved these changes
привет!
работа принята

2023-07-04 22:00 UTC, merged