Add item requests
DmitriiLebedev/java-shareit pull request #13
Opened 2023-07-20 21:44 UTC by DmitriiLebedev

2023-07-22 08:44 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
Но ты забыл пару эндпойнтов обновить

2023-07-22 08:44 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemBookingModel> findAllItemsByOwner(@RequestHeader("X-Sharer-User-Id") Long ownerId) {
здесь забыли пагинацию

2023-07-22 08:44 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @GetMapping("/search")
здесь забыли пагинацию

2023-07-22 16:49 UTC, DmitriiLebedev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @GetMapping("/search")
Постман не ругался, я и забыл)

2023-07-23 05:39 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-08-22 20:02 UTC, merged